---
format:
  modern2-cover-letter-pdf: default
author: Roussaffa Hugo
date: today
date-format: long
lang: fr

cvfont: raleway #texlive fonts like raleway,fetamont,gillius,comfortaa
cvcolor: 
  main: B83B5E
  accent: 6A2C70
  
title: Lettre de motivation
sub-title: 'Candidature au poste de géomaticien et responsable de projets'

contact:
  street: 3 chemin de Rouyre Haut
  zip: 11400
  city: Verdun-en-Lauragais 
  phone: +33 659865534
  mail: hugoroussaffa@gmail.com 
  
organization:
  contact-person: Monsieur le coordinateur 
  name: Association TIGEO
  street: 15 Rue de Jautzou
  zip: 81000 
  city: Albi
    
---

  Monsieur Lionel VIGUIER,

Avec environ 15 ans d'expérience en géomatique et en gestion de projet, je suis aujourd'hui à la recherche d'un poste qui me permette de retrouver un cadre professionnel à taille humaine, assez proche de mon domicile, en phase avec mes valeurs et avec une prise de fonction rapide. TIGEO réunit ces critères, notamment par votre engagement dans la valorisation des données géographiques et la mutualisation des compétences clés au service des acteurs des politiques publiques tarnaises. Je déduit que le projet DFCI est un partenariat d'Assistance à Maîtrise d'Ouvrage pour la sécurité civile, ce qui est totalement aligné à mon profil de part mes experiences passées, précisement sur la thématiques des incendies, ce qui pourrait consolider le rôle de TIGEO sur son territoire.

Titulaire d'un Master 2 en sciences humaines spécialisé en géomatique, j'ai acquis une solide expérience en gestion de bases de données spatiales, développement d’applications cartographiques, architecture et administration de SIG. Polyvalent, je suis à l'aise aussi bien avec les solutions libres que propriétaires (ESRI). Reconnû pour être force de proposition, j'aime apporter des solutions pragmatiques aux problèmes existants. J'ai déjà mené plusieurs projets en tant qu'assistant à maîtrise d'ouvrage, responsable technique ou développeur, tant en acquisition de données par télédétection que par application mobile destinée à des agents de terrain. J'ai à ces occasions été en lien avec des acteurs publics, associatifs ou privés. Ces collaborations ont permis de réaliser des supports décisonnels pertinents et performant à long terme. Je vous invite à consulter quelques exemples de resultats dans mon portfolio [*en suivant ce lien*](https://yougis.github.io/portfolio-hugo/fr/).

Le projet de déploiement de la base de données géographiques sur la DFCI me semble à la fois technique et concret, ce qui correspond à ce que j'apprécie dans mon travail. Mon expérience en nettoyage, structuration et alimentation de bases PostgreSQL/PostGIS, couplée à mes compétences en automatisation via Python et SQL, me permettrait d’apporter une contribution immédiate et techniquement avancée. J'ai aussi un intérêt particulier pour le développement d’interfaces de visualisation de données ou de projet QGIS tel que Lizmap, ainsi que la création de scripts, ce qui correspond aux activités mentionnées dans votre annonce. Ma méthodologie de travail répond aux exigences de documentation et de tranfert de connaissance.

Je souhaite aujourd’hui m’investir pleinement dans votre structure, offrant un cadre de travail stimulant et en phase avec mes compétences. J’apprécie particulièrement le travail en milieu associatif, petite équipe, où la polyvalance, la collaboration et les liens de proximité avec les acteurs du territoire sont essentiels.

Je serai en France à partir du 15 mai et en mesure d’être opérationnel rapidement. Concernant mes prétentions salariales, bien que concient d'être sûr qualifié vis à vis d'un technicien, je souhaite un salaire réévalué à seulement 2600 euros nets mensuel, je suis toutefois ouvert à la discussion, notamment si des avantages supplémentaires peuvent être envisagés pour améliorer la proposition. Je suis en contrepartie bien entendu prêt à apporter toute mon expérience et mon expertise pour aller au-delà du simple cahier des charges du poste et d’apporter mes conseils et compétences stratégiques au développement du système d'information de votre structure.

Je serais ravi d’échanger avec vous sur mon parcours et ma motivation en premier lieu lors d'un entretien en visio.

Sincèrement,
Hugo Roussaffa