---
author:
  - name: Roussaffa Hugo
    affiliation:
      - name:  CONSEIL DEPARTEMENTAL DE LA HAUTE-GARONNE
        department: 
        address: 1 BOULEVARD DE LA MARQUETTE 
        city: Toulouse 
        country: France
        postal-code: 31000
address:
  - Hugo Roussaffa
  - 3 chemin de Rouyre Haut
  - Verdun-en-Lauragais 11400

subject-title: Référent Système d'Information
subject-suffix: "&nbsp;:"

opening: "Objet : Candidature au poste de Référent Système d'Information - Offre n° O031250424001280"
closing: "Sincèrement,"


lang: fr

format: letter-pdf
---

Objet : Candidature au poste d’administrateur système d’information et de télécommunication


Madame, Monsieur,


Expert en géomatique, je suis intervenu sur l’ensemble de la chaîne de gestion des données au court de ces 15 derni1ères années: de l’administration de bases (PostgreSQL/PostGIS, SQL Server) à la sécurisation des flux, en passant par l’automatisation des traitements avec Python et SQL. J’ai souvent travaillé dans des environnements hybrides, combinant serveurs Linux et Windows, dans des contextes nécessitant à la fois rigueur, documentation et capacité à intervenir sur des architectures distribuées.

La mission data au sein de Meteo France va nécéciter de gérer des systèmes complexes, de maintenir des infrastructures télécoms et de garantir la continuité de service. J’ai eu à assurer ce type de missions, notamment dans le cadre de plateformes de diffusion de données ou d’outils décisionnels en production, avec surveillance, gestion des droits, protocoles de sécurité, et appui aux utilisateurs.

J’ai également travaillé dans des contextes soumis à des contraintes de disponibilité et de fiabilité, notamment pour des projets en lien avec la prévention des risques environnementaux. Je suis donc sensibilisé à l’importance de la robustesse des systèmes d’information, de la supervision, et de la documentation des procédures. La collaboration interservices, tout comme l’accompagnement des utilisateurs, fait également partie de mon quotidien professionnel.

Enfin, je suis autonome, rigoureux, à l’aise dans la communication orale comme écrite, et capable d’apprendre rapidement de nouveaux outils ou protocoles. Mon profil polyvalent et ma connaissance des environnements techniques me permettent d’être immédiatement opérationnel tout en m’intégrant facilement dans une équipe.

Je suis disponible rapidement et reste à votre disposition pour tout échange ou entretien.
